[package]
name = "bevy_easy_compute"
version = "0.14.0"
authors = [
    "Cornchip <cornchipgonecodin@gmail.com>",
    "Kjolnyr <kjolnyr@protonmail.com>",
]
edition = "2021"
description = "An easy way to run compute shaders for Bevy"
repository = "https://github.com/AnthonyTornetta/bevy_easy_compute"
homepage = "https://github.com/AnthonyTornetta/bevy_easy_compute"
documentation = "https://docs.rs/bevy_easy_compute"
license = "MIT OR Apache-2.0"
readme = "README.md"
categories = ["game-development"]

[features]
shader_format_spirv = []
webgl = []

[lib]
doctest = false

[dependencies]
bevy = "0.14"
parking_lot = ">=0.12.3"
wgpu = { version = "0.20.1", features = ["naga", "spirv"] }
bytemuck = ">=1.16.1"
naga = { version = "0.20.0", features = ["wgsl-in"] }
naga_oil = { version = ">=0.14.0", default-features = false, features = [
    "test_shader",
] }

[dev-dependencies]
rand = ">=0.8.5"
bevy = { version = "0.14", features = ["wayland"] }

[[example]]
name = "simple"

[[example]]
name = "multi_pass"

[[example]]
name = "one_shot"

[[example]]
name = "boids"
